# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyUICBasicDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys

IMAGE_WIDTH, IMAGE_HEIGHT = 660, 371

class Ui_MainWindow(object):
    def __init__(self):
        self.selected_folder_path = ''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 780)
        
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")

        self.ComboDevices = QtWidgets.QComboBox(self.centralWidget)
        self.ComboDevices.setGeometry(QtCore.QRect(700, 23, 211, 22))
        self.ComboDevices.setObjectName("ComboDevices")

        self.widgetDisplay = QtWidgets.QWidget(self.centralWidget)
        self.widgetDisplay.setGeometry(QtCore.QRect(10, 20, 660, 660))
        self.widgetDisplay.setObjectName("widgetDisplay")

        self.labelDisplay = QtWidgets.QLabel(self.widgetDisplay)
        self.labelDisplay.setGeometry(0, 5, IMAGE_WIDTH, IMAGE_HEIGHT)   
        self.labelDisplay.setObjectName("labelDisplay")

        self.labelDisplay.setStyleSheet("border: 2px solid gray;")

        self.groupInit = QtWidgets.QGroupBox(self.centralWidget)
        self.groupInit.setGeometry(QtCore.QRect(700, 50, 211, 101))
        self.groupInit.setObjectName("groupInit")

        self.gridLayoutWidget = QtWidgets.QWidget(self.groupInit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 201, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")

        self.bnClose = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bnClose.setEnabled(False)
        self.bnClose.setObjectName("bnClose")
        self.gridLayout.addWidget(self.bnClose, 2, 2, 1, 1)

        self.bnOpen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bnOpen.setEnabled(False)
        self.bnOpen.setObjectName("bnOpen")
        self.gridLayout.addWidget(self.bnOpen, 2, 1, 1, 1)

        self.bnEnum = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bnEnum.setEnabled(True)
        self.bnEnum.setObjectName("bnEnum")
        self.gridLayout.addWidget(self.bnEnum, 1, 1, 1, 2)

        self.groupGrab_1 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupGrab_1.setEnabled(False)
        self.groupGrab_1.setGeometry(QtCore.QRect(700, 290, 211, 150))
        self.groupGrab_1.setObjectName("groupGrab")

        self.gridLayoutWidget_2_1 = QtWidgets.QWidget(self.groupGrab_1)
        self.gridLayoutWidget_2_1.setGeometry(QtCore.QRect(5, 12, 200, 140))
        self.gridLayoutWidget_2_1.setObjectName("gridLayoutWidget_2")

        self.gridLayout_2_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_2_1)
        self.gridLayout_2_1.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2_1.setSpacing(1)
        self.gridLayout_2_1.setObjectName("gridLayout_2")

        self.radioTriggerMode = QtWidgets.QRadioButton(self.gridLayoutWidget_2_1)
        self.radioTriggerMode.setObjectName("radioTriggerMode")
        self.gridLayout_2_1.addWidget(self.radioTriggerMode, 0, 0, 1, 1)

        self.bnSoftwareTrigger = QtWidgets.QPushButton(self.gridLayoutWidget_2_1)
        self.bnSoftwareTrigger.setEnabled(False)
        self.bnSoftwareTrigger.setObjectName("bnSoftwareTrigger")
        self.gridLayout_2_1.addWidget(self.bnSoftwareTrigger, 1, 0, 1, 2)

        self.bnSaveImage = QtWidgets.QPushButton(self.gridLayoutWidget_2_1)
        self.bnSaveImage.setEnabled(False)
        self.bnSaveImage.setObjectName("bnSaveImage")
        self.gridLayout_2_1.addWidget(self.bnSaveImage, 2, 0, 1, 2)

        self.folder_path_entry = QtWidgets.QLineEdit(self.gridLayoutWidget_2_1)
        self.folder_path_entry.setReadOnly(True)
        self.gridLayout_2_1.addWidget(self.folder_path_entry, 3, 0, 1, 2)

        self.bnFolderBrowser = QtWidgets.QPushButton(self.gridLayoutWidget_2_1)
        self.bnFolderBrowser.setText("Browse Folder")
        self.gridLayout_2_1.addWidget(self.bnFolderBrowser, 3, 1, 1, 1)

        self.checkbox = QCheckBox("Check Option", self.gridLayoutWidget_2_1)
        self.gridLayout_2_1.addWidget(self.checkbox, 4, 0, 1, 1)

        self.groupGrab = QtWidgets.QGroupBox(self.centralWidget)
        self.groupGrab.setEnabled(False)
        self.groupGrab.setGeometry(QtCore.QRect(700, 170, 211, 110))
        self.groupGrab.setObjectName("groupGrab")

        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupGrab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(5, 12, 200, 100))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.radioContinueMode = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioContinueMode.setObjectName("radioContinueMode")
        self.gridLayout_2.addWidget(self.radioContinueMode, 0, 0, 1, 1)

        self.bnStop = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.bnStop.setEnabled(False)
        self.bnStop.setObjectName("bnStop")
        self.gridLayout_2.addWidget(self.bnStop, 1, 1, 1, 1)

        self.bnStart = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.bnStart.setEnabled(False)
        self.bnStart.setObjectName("bnStart")
        self.gridLayout_2.addWidget(self.bnStart, 1, 0, 1, 1)

        self.fullScreenButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.fullScreenButton.setObjectName("fullScreenButton")
        self.fullScreenButton.setText("Full Screen")
        self.gridLayout_2.addWidget(self.fullScreenButton,2, 0, 1, 1)

        self.groupParam = QtWidgets.QGroupBox(self.centralWidget)
        self.groupParam.setEnabled(False)
        self.groupParam.setGeometry(QtCore.QRect(700, 450, 211, 300))
        self.groupParam.setObjectName("groupParam")

        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupParam)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 201, 300))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")

        self.gridLayoutParam = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayoutParam.setContentsMargins(11, 11, 11, 11)
        self.gridLayoutParam.setSpacing(0)
        self.gridLayoutParam.setObjectName("gridLayoutParam")

        #user set load
        self.label_usersetload = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_usersetload.setObjectName("label usersetload")
        self.gridLayoutParam.addWidget(self.label_usersetload, 0, 0, 1, 1)

        self.combo_usersetload = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.combo_usersetload.setObjectName("User Set Load")
        self.combo_usersetload.addItems(["Default","UserSet1", "UserSet2","UserSet3","UserSet4"])  
        self.gridLayoutParam.addWidget(self.combo_usersetload, 0, 1, 1, 1)

        #width
        self.label_width = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_width.setObjectName("label_width")
        self.gridLayoutParam.addWidget(self.label_width, 1, 0, 1, 1)

        self.edtwidth = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.edtwidth.setObjectName("edtwidth")
        self.gridLayoutParam.addWidget(self.edtwidth, 1, 1, 1, 1)

        #height
        self.label_height = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_height.setObjectName("label_height")
        self.gridLayoutParam.addWidget(self.label_height, 2, 0, 1, 1)

        self.edtheight = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.edtheight.setObjectName("edtheight")
        self.gridLayoutParam.addWidget(self.edtheight, 2, 1, 1, 1)

        #OffsetX
        self.label_OffsetX = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_OffsetX.setObjectName("label_OffsetX")
        self.gridLayoutParam.addWidget(self.label_OffsetX, 3, 0, 1, 1)

        self.edtOffsetX = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.edtOffsetX.setObjectName("edtOffsetX")
        self.gridLayoutParam.addWidget(self.edtOffsetX, 3, 1, 1, 1)

        #OffsetY
        self.label_OffsetY = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_OffsetY.setObjectName("label_OffsetY")
        self.gridLayoutParam.addWidget(self.label_OffsetY, 4, 0, 1, 1)

        self.edtOffsetY = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.edtOffsetY.setObjectName("edtOffsetY")
        self.gridLayoutParam.addWidget(self.edtOffsetY, 4, 1, 1, 1)

        #ExposureTime
        self.label_ExposureTime = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_ExposureTime.setObjectName("label_ExposureTime")
        self.gridLayoutParam.addWidget(self.label_ExposureTime, 5, 0, 1, 1)

        self.edtExposureTime = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.edtExposureTime.setObjectName("edtExposureTime")
        self.gridLayoutParam.addWidget(self.edtExposureTime, 5, 1, 1, 1)

        #Gain
        self.label_Gain = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_Gain.setObjectName("label_Gain")
        self.gridLayoutParam.addWidget(self.label_Gain, 6, 0, 1, 1)

        self.edtGain = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.edtGain.setObjectName("edtGain")
        self.gridLayoutParam.addWidget(self.edtGain, 6, 1, 1, 1)

        #FrameRate
        self.label_FrameRate = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_FrameRate.setObjectName("label_FrameRate")
        self.gridLayoutParam.addWidget(self.label_FrameRate, 7, 0, 1, 1)

        self.edtFrameRate = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.edtFrameRate.setObjectName("edtFrameRate")
        self.gridLayoutParam.addWidget(self.edtFrameRate, 7, 1, 1, 1)

        self.bnGetParam = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.bnGetParam.setObjectName("bnGetParam")
        self.gridLayoutParam.addWidget(self.bnGetParam, 9, 0, 1, 1)

        self.bnSetParam = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.bnSetParam.setObjectName("bnSetParam")
        self.gridLayoutParam.addWidget(self.bnSetParam, 9, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def openFullScreenWindow(self):
        # Create a new window for full-screen display
        self.fullScreenWindow = QtWidgets.QMainWindow()
        self.fullScreenWindow.setWindowTitle("Full Screen Display")

        # Set window size to screen size
        screen_geometry = QtWidgets.QApplication.desktop().screenGeometry()
        self.fullScreenWindow.setGeometry(screen_geometry)

        # Label in the full-screen window
        self.fullScreenLabel = QtWidgets.QLabel(self.fullScreenWindow)
        self.fullScreenLabel.setGeometry(0, 0, screen_geometry.width(), screen_geometry.height())
        self.fullScreenLabel.setStyleSheet("border: 2px solid gray; background-color: black;")

        self.closeButton = QtWidgets.QPushButton("X", self.fullScreenWindow)
        self.closeButton.setGeometry(screen_geometry.width() - 50, 10, 40, 30)  # Position it at the top right corner
        self.closeButton.setStyleSheet("background-color: red; color: white; border: none;")
        self.closeButton.clicked.connect(self.fullScreenWindow.close)

        # Show full-screen window
        self.fullScreenWindow.showFullScreen()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pylon Viewer"))
        self.groupInit.setTitle(_translate("MainWindow", "Initialization"))
        self.bnClose.setText(_translate("MainWindow", "Destroy Device"))
        self.bnOpen.setText(_translate("MainWindow", "Connect Device"))
        self.bnEnum.setText(_translate("MainWindow", "Collect Device"))
        self.groupGrab.setTitle(_translate("MainWindow", "Streaming"))
        self.groupGrab_1.setTitle(_translate("MainWindow", "Trigger Once"))
        self.bnSaveImage.setText(_translate("MainWindow", "Save Single Image"))
        self.folder_path_entry.setText(_translate("MainWindow", " **/*.jpg"))
        self.bnFolderBrowser.setText(_translate("MainWindow", "Browse Folder"))
        self.checkbox.setText(_translate("MainWindow", "Save Image"))
        self.radioContinueMode.setText(_translate("MainWindow", "Mode on"))
        self.radioTriggerMode.setText(_translate("MainWindow", "Mode on"))
        self.bnStop.setText(_translate("MainWindow", "Stop"))
        self.bnStart.setText(_translate("MainWindow", "Start"))
        self.bnSoftwareTrigger.setText(_translate("MainWindow", "Trigger"))
        self.groupParam.setTitle(_translate("MainWindow", "Parameter"))
        self.label_usersetload.setText(_translate("MainWindow", "User Set Load"))
        self.label_width.setText(_translate("MainWindow", "Width"))
        self.label_height.setText(_translate("MainWindow", "Height"))
        self.label_OffsetX.setText(_translate("MainWindow", "Offset X"))
        self.label_OffsetY.setText(_translate("MainWindow", "Offset Y"))
        self.label_ExposureTime.setText(_translate("MainWindow", "ExposureTime"))
        self.label_Gain.setText(_translate("MainWindow", "Gain"))
        self.label_FrameRate.setText(_translate("MainWindow", "FrameRate"))
        self.edtwidth.setText(_translate("MainWindow", "0"))
        self.edtheight.setText(_translate("MainWindow", "0"))
        self.edtOffsetX.setText(_translate("MainWindow", "0"))
        self.edtOffsetY.setText(_translate("MainWindow", "0"))
        self.edtExposureTime.setText(_translate("MainWindow", "0"))
        self.edtGain.setText(_translate("MainWindow", "0"))
        self.edtFrameRate.setText(_translate("MainWindow", "0"))
        self.bnGetParam.setText(_translate("MainWindow", "Export"))
        self.bnSetParam.setText(_translate("MainWindow", "Save"))
        