# Generated by Django 4.2.1 on 2024-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_VID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_all', models.IntegerField(blank=True, null=True)),
                ('size_detection', models.IntegerField(blank=True, null=True)),
                ('label_name', models.CharField(blank=True, max_length=255, null=True)),
                ('join_detect', models.BooleanField(blank=True, default=False, null=True)),
                ('OK', models.BooleanField(blank=True, default=False, null=True)),
                ('NG', models.BooleanField(blank=True, default=False, null=True)),
                ('num_labels', models.IntegerField(blank=True, null=True)),
                ('width_min', models.IntegerField(blank=True, null=True)),
                ('width_max', models.IntegerField(blank=True, null=True)),
                ('height_min', models.IntegerField(blank=True, null=True)),
                ('height_max', models.IntegerField(blank=True, null=True)),
                ('return_value', models.IntegerField(blank=True, null=True)),
                ('cmpnt_conf', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
