# Generated by Django 5.1 on 2024-09-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_connection", "0002_model_vid"),
    ]

    operations = [
        migrations.AddField(
            model_name="model1",
            name="rotage_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="model1",
            name="rotage_min",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
